export const ITEMS = {
    // МАТЕРИАЛЫ
    'wood': { id: 'wood', name: 'Дерево', description: 'Обычная древесина для крафта', lore: 'Материал, проверенный временем. Пахнет лесом и возможностями.', price: 40, sellPrice: 8, type: 'material', rarity: 'common', icon: '<:wood:1487407591729532938>', craftable: false },
    'iron': { id: 'iron', name: 'Железо', description: 'Кусок необработанного железа', lore: 'Ржавое, но всё еще крепкое. Нужно переплавить во что-то полезное.', price: 80, sellPrice: 15, type: 'material', rarity: 'common', icon: '<:iron:1487408314953240607>', craftable: false },
    'electronic_part': { id: 'electronic_part', name: 'Электроника', description: 'Набор транзисторов и плат', lore: 'Сложные схемы, извлеченные из старых терминалов.', price: 200, sellPrice: 40, type: 'material', rarity: 'uncommon', icon: '<:electronic_part:1487408982623653888>', craftable: false },
    'star_dust': { id: 'star_dust', name: 'Звездная пыль', description: 'Базовый материал для крафта', lore: 'Остатки упавшего метеорита. Говорят, если собрать её в ладони, можно почувствовать тепло далеких галактик.', price: 50, sellPrice: 10, type: 'material', rarity: 'common', icon: '<:star_dust:1487409214392369282>', craftable: false },
    'iron_ingot': { id: 'iron_ingot', name: 'Слиток железа', description: 'Прочный металл для создания простых ключей', lore: 'Холодный и тяжелый. Основа любой индустрии.', price: 100, sellPrice: 20, type: 'material', rarity: 'common', icon: '<:iron_ingot:1487409340657963088>', craftable: true, recipe: [{ itemId: 'iron', amount: 3 }, { itemId: 'wood', amount: 2 }] },
    'gold_ingot': { id: 'gold_ingot', name: 'Слиток золота', description: 'Драгоценный металл', lore: 'В древности из него делали короны, а теперь это важнейший проводник для квантовых технологий.', price: 250, sellPrice: 50, type: 'material', rarity: 'uncommon', icon: '<:gold_ingot:1487409486607024209>', craftable: true, recipe: [{ itemId: 'iron_ingot', amount: 3 }, { itemId: 'star_dust', amount: 5 }] },
    'magic_powder': { id: 'magic_powder', name: 'Магический порошок', description: 'Странно светится. Нужен для бустеров', lore: 'Пахнет озоном и слегка покалывает пальцы. Алхимики прошлого отдали бы за него жизнь.', price: 150, sellPrice: 30, type: 'material', rarity: 'uncommon', icon: '<:magic_powder:1487409727662198876>', craftable: true, recipe: [{ itemId: 'star_dust', amount: 5 }] },
    'neon_tube': { id: 'neon_tube', name: 'Неоновая трубка', description: 'Светящийся элемент для кибер-крафта', lore: 'Осколок вывески из Найт-Сити. Внутри пульсирует чистая энергия.', price: 200, sellPrice: 40, type: 'material', rarity: 'uncommon', icon: '<:neon_tube:1487409997683097730>', craftable: true, recipe: [{ itemId: 'electronic_part', amount: 2 }, { itemId: 'star_dust', amount: 3 }] },
    'cyber_part': { id: 'cyber_part', name: 'Кибер-деталь', description: 'Высокотехнологичный компонент', lore: 'Никто точно не знает, как она работает, но без неё не собрать ни одну продвинутую схему.', price: 300, sellPrice: 60, type: 'material', rarity: 'rare', icon: '<:cyber_part:1487410152062845050>', craftable: true, recipe: [{ itemId: 'electronic_part', amount: 3 }, { itemId: 'iron_ingot', amount: 2 }] },
    'ancient_scroll': { id: 'ancient_scroll', name: 'Древний свиток', description: 'Содержит забытые знания', lore: 'Пергамент рассыпается в руках, но руны на нём всё ещё светятся тусклым светом.', price: 600, sellPrice: 120, type: 'material', rarity: 'rare', icon: '<:ancient_scroll:1487410264319066253>', craftable: false },
    'quantum_chip': { id: 'quantum_chip', name: 'Квантовый чип', description: 'Вычислительная мощь будущего', lore: 'В этом крошечном кристалле больше вычислительной мощности, чем во всех компьютерах Земли 21 века.', price: 1200, sellPrice: 250, type: 'material', rarity: 'epic', icon: '<:quantum_chip:1487410425074028646>', craftable: true, recipe: [{ itemId: 'cyber_part', amount: 3 }, { itemId: 'gold_ingot', amount: 2 }] },
    'crystal_core': { id: 'crystal_core', name: 'Кристальное ядро', description: 'Излучает мощную энергию', lore: 'Бьется словно живое сердце. Если прислушаться, можно услышать шепот.', price: 1000, sellPrice: 200, type: 'material', rarity: 'epic', icon: '<:crystal_core:1487410660743712779>', craftable: true, recipe: [{ itemId: 'magic_powder', amount: 5 }, { itemId: 'star_dust', amount: 20 }] },
    'dark_matter': { id: 'dark_matter', name: 'Темная материя', description: 'Самый редкий ресурс во вселенной', lore: 'Она поглощает свет вокруг себя. Держать её голыми руками категорически запрещено.', price: 5000, sellPrice: 1000, type: 'material', rarity: 'legendary', icon: '<:dark_matter:1487410832802582759>', craftable: false },
    'key_fragment': { id: 'key_fragment', name: 'Фрагмент ключа', description: 'Соберите 3 фрагмента, чтобы скрафтить Ключ', lore: 'Осколок чего-то большего. Сам по себе бесполезен, но в правильных руках открывает любые двери.', price: 200, sellPrice: 40, type: 'material', rarity: 'uncommon', icon: '<:key_fragment:1487411150676168877>', craftable: false },

    // ЛУТБОКСЫ И КЛЮЧИ
    'daily_bag': { id: 'daily_bag', name: 'Ежедневный мешок', description: 'Бесплатный мешок с ресурсами', lore: 'Никто не знает, кто оставляет эти мешки у вашей двери каждое утро.', price: 0, sellPrice: 0, type: 'lootbox', rarity: 'common', icon: '🛍️', craftable: false },
    'bronze_chest': { id: 'bronze_chest', name: 'Бронзовый сундук', description: 'Обычный сундук', lore: 'Покрыт патиной и слегка пахнет сыростью.', price: 300, sellPrice: 50, type: 'lootbox', rarity: 'common', icon: '🧰', craftable: true, recipe: [{ itemId: 'wood', amount: 10 }, { itemId: 'iron', amount: 2 }] },
    'bronze_key': { id: 'bronze_key', name: 'Бронзовый ключ', description: 'Открывает Бронзовый сундук', lore: 'Грубая работа, но со своей задачей справляется.', price: 150, sellPrice: 30, type: 'key', rarity: 'common', icon: '🗝️', craftable: true, recipe: [{ itemId: 'iron_ingot', amount: 2 }] },
    'silver_chest': { id: 'silver_chest', name: 'Серебряный сундук', description: 'Хороший лут', lore: 'На крышке выгравированы странные символы.', price: 800, sellPrice: 150, type: 'lootbox', rarity: 'uncommon', icon: '🗃️', craftable: true, recipe: [{ itemId: 'bronze_chest', amount: 2 }, { itemId: 'iron_ingot', amount: 5 }] },
    'silver_key': { id: 'silver_key', name: 'Серебряный ключ', description: 'Открывает Серебряный сундук', lore: 'Идеально сбалансирован для вскрытия сложных механизмов.', price: 400, sellPrice: 80, type: 'key', rarity: 'uncommon', icon: '🗝️', craftable: true, recipe: [{ itemId: 'bronze_key', amount: 2 }, { itemId: 'iron_ingot', amount: 3 }] },
    'cyber_box': { id: 'cyber_box', name: 'Кибер-кейс', description: 'Высокотехнологичный контейнер', lore: 'Защищен 1024-битным шифрованием.', price: 2000, sellPrice: 400, type: 'lootbox', rarity: 'epic', icon: '🕋', craftable: false },
    'cyber_key': { id: 'cyber_key', name: 'Кибер-ключ', description: 'Взламывает Кибер-кейс', lore: 'Специальный вирус-дешифратор на квантовом носителе.', price: 1000, sellPrice: 200, type: 'key', rarity: 'epic', icon: '📟', craftable: true, recipe: [{ itemId: 'cyber_part', amount: 2 }, { itemId: 'quantum_chip', amount: 1 }] },
    'mystery_box': { id: 'mystery_box', name: 'Мистический сундук', description: 'Содержит редчайшие предметы', lore: 'Он периодически исчезает из инвентаря.', price: 1500, sellPrice: 300, type: 'lootbox', rarity: 'rare', icon: '🎁', craftable: true, recipe: [{ itemId: 'silver_chest', amount: 3 }, { itemId: 'magic_powder', amount: 10 }] },
    'mystery_key': { id: 'mystery_key', name: 'Мистический ключ', description: 'Открывает Мистический сундук', lore: 'Ключ, который меняет свою форму.', price: 500, sellPrice: 100, type: 'key', rarity: 'rare', icon: '🔑', craftable: true, recipe: [{ itemId: 'key_fragment', amount: 3 }] },
    'legendary_cache': { id: 'legendary_cache', name: 'Тайник Легенд', description: 'Гарантированный Эпик или Легендарка', lore: 'Потерянный артефакт забытой цивилизации.', price: 10000, sellPrice: 2000, type: 'lootbox', rarity: 'legendary', icon: '🏆', craftable: false },
    'season_case': { id: 'season_case', name: 'Сезонный кейс', description: 'Эксклюзивные награды Боевого Пропуска', lore: 'Контейнер за особые заслуги перед фракциями.', price: 0, sellPrice: 400, type: 'lootbox', rarity: 'epic', icon: '📦', craftable: false },

    // БУСТЕРЫ
    'cyber_chip': { id: 'cyber_chip', name: 'Кибер-чип', description: 'Ключ доступа к закрытым системам', lore: 'Используется для запуска команды /hack.', price: 500, sellPrice: 100, type: 'consumable', rarity: 'rare', icon: '💾', craftable: false },
    'luck_potion': { id: 'luck_potion', name: 'Зелье Удачи', description: 'Повышает шанс лута на 10%', lore: 'На вкус как жидкая лотерея.', price: 600, sellPrice: 120, type: 'consumable', rarity: 'rare', icon: '🧪', craftable: true, recipe: [{ itemId: 'magic_powder', amount: 3 }, { itemId: 'star_dust', amount: 10 }] },
    'xp_boost_small': { id: 'xp_boost_small', name: 'Малый энергетик', description: '+25% к опыту БП на 1 час', lore: 'Дешевый кофеин и немного сахара.', price: 300, sellPrice: 50, type: 'consumable', rarity: 'uncommon', icon: '🥤', craftable: false },
    'xp_boost_large': { id: 'xp_boost_large', name: 'Большой энергетик', description: '+50% к опыту БП на 3 часа', lore: 'Запрещен во многих киберспортивных лигах.', price: 1000, sellPrice: 200, type: 'consumable', rarity: 'epic', icon: '⚡', craftable: true, recipe: [{ itemId: 'xp_boost_small', amount: 3 }, { itemId: 'magic_powder', amount: 1 }] },
    'xp_boost_mega': { id: 'xp_boost_mega', name: 'Квантовый ускоритель', description: '+100% к опыту БП на 6 часов', lore: 'Искажает восприятие времени.', price: 3000, sellPrice: 600, type: 'consumable', rarity: 'legendary', icon: '🚀', craftable: true, recipe: [{ itemId: 'xp_boost_large', amount: 2 }, { itemId: 'quantum_chip', amount: 1 }] },
    'star_contract': { id: 'star_contract', name: 'Звездный контракт', description: 'x2 получение Звезд на 2 часа', lore: 'Официальный документ Межгалактического Банка.', price: 1500, sellPrice: 300, type: 'consumable', rarity: 'rare', icon: '📜', craftable: true, recipe: [{ itemId: 'ancient_scroll', amount: 1 }, { itemId: 'gold_ingot', amount: 3 }] },
    'star_contract_premium': { id: 'star_contract_premium', name: 'Контракт Монополиста', description: 'x4 получение Звезд на 3 часа', lore: 'Позволяет законно обдирать экономику сервера.', price: 5000, sellPrice: 1000, type: 'consumable', rarity: 'epic', icon: '📈', craftable: true, recipe: [{ itemId: 'star_contract', amount: 3 }, { itemId: 'dark_matter', amount: 1 }] },
    'anti_mute_shield': { id: 'anti_mute_shield', name: 'Щит свободы', description: 'Одноразово отменяет выданный мут', lore: 'Блокирует попытки закрыть вам рот.', price: 5000, sellPrice: 1000, type: 'consumable', rarity: 'legendary', icon: '🛡️', craftable: true, recipe: [{ itemId: 'crystal_core', amount: 3 }, { itemId: 'cyber_part', amount: 5 }] },
    'custom_role_ticket': { id: 'custom_role_ticket', name: 'Билет Создателя', description: 'Создание личной роли', lore: 'Золотой билет в историю сервера.', price: 50000, sellPrice: 10000, type: 'consumable', rarity: 'mythic', icon: '🎫', craftable: false }
};

export const getItemDefinition = (itemId) => {
    const item = ITEMS[itemId];
    if (!item) return { name: 'Неизвестно', icon: '❓', description: 'Предмет не найден' };

    let displayIcon = item.icon;
    const discordEmojiRegex = /<:([^:]+):(\d+)>/;
    const match = item.icon.match(discordEmojiRegex);
    if (match) {
        displayIcon = `<img src="https://cdn.discordapp.com/emojis/${match[2]}.webp?size=64" alt="${match[1]}" class="item-emoji-img" style="width: 1em; height: 1em; vertical-align: middle;">`;
    }

    return { ...item, displayIcon };
};